### PR TITLE
Create my first workflow

### PR DESCRIPTION
**Pull request by jayakumark**
Workflow files are the recipe for task automation. This is where actions are placed if I want to use them for a task.

### CODE REVIEW

**Review by jayakumark — COMMENTED** [review]
Approved

**Review by jkfnc — APPROVED** [review]
approved

**Review by jkfnc — APPROVED** [review]

**Review by jkfnc — APPROVED** [review]
Approved

**Review by jkfnc — APPROVED** [review]

**Review by jkfnc — APPROVED** [review]

**Review by jayakumark — COMMENTED** [review]
approve

**Review by jayakumark — COMMENTED** [review]
reviw

**Pull request merged**
